import Head from 'next/head';
import CatalogConfig from '@/components/CatalogConfig/CatalogConfig';
export default function Home() {
  return (
    <>
      <Head>
        <title>CATALOG</title>
        <meta name='description' content='Generated by catalog' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link
          rel='icon'
          href='https://bsscommerce.com/media/favicon/stores/1/icon-bss.png'
        />
      </Head>
      <div className=''>
        <main className=''>
          <CatalogConfig />
        </main>
      </div>
    </>
  );
}
