import Head from 'next/head';
import CatalogConfig from '@/components/CatalogConfig/CatalogConfig';
import Search from '@/components/Search/Search';
import { useEffect } from 'react';
import { useRouter } from 'next/router';
import { parseCookies } from 'nookies';

export default function Home() {
  const router = useRouter();
  useEffect(() => {
    const cookies = parseCookies();
    if (!cookies.accessToken) {
      router.push('/login');
    }
  }, [router]);

  return (
    <>
      <Head>
        <title>CATALOG</title>
        <meta name='description' content='Generated by catalog' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link
          rel='icon'
          href='https://bsscommerce.com/media/favicon/stores/1/icon-bss.png'
        />
      </Head>
      <div className=''>
        <main className='App'>
          <Search />
          <CatalogConfig />
        </main>
      </div>
    </>
  );
}
